# Generated by Django 6.0.1 on 2026-04-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('container', 'index')},
        ),
    ]
