# Generated by Django 6.0.1 on 2026-04-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.container'),
        ),
        migrations.CreateModel(
            name='AnotherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('index', models.PositiveSmallIntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.container')),
            ],
            options={
                'ordering': ('container', 'index'),
                'abstract': False,
            },
        ),
    ]
